#!/bin/sh

SCRIPT="/oem/usr/bin/bitsybox"
RUNAS="root"
PIDFILE="/var/run/bitsybox.pid"
LOGFILE="/var/log/bitsybox.log"

export SDL_AUDIODRIVER="dummy"

start() {
  if [ -f "$PIDFILE" ] && kill -0 $(cat "$PIDFILE"); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service...' >&2
  su -c "$SCRIPT &> \"$LOGFILE\" & echo \$! > \"$PIDFILE\"" "$RUNAS"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service...' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac